## APPLICATION BROWSER
#browser = chrome
## APPLICATION URL
#url=https://www.demoblaze.com/
## APPLICATION USERNAME AND PASSWORD
#username=vivekanand
#password=vivek@123
#screenshort=.//Screenshot//
# BROWSER USED FOR SCRIPT
browser=chrome
# APPLICATION TO BE LAUNCH
url=https://www.demoblaze.com/
# APPLICATION LOGIN CREDENTIALS
username=vivekvinoth
password=vinoth@123
screenshot=.//Screenshot//
#ORDER PLACING DETAILS
name=vivek
country=India
city=Chennai
creditCard=1234567890000
month=01
year=2026